### ISSUE TITLE
nswag, auto generation of service proxy for non curd apps

### ISSUE THREAD

**Issue by mawroos** [sachatrauwaen/OpenApp#3]
Hi,
I love your project, and its working for me, but now I'm creating an appservice that is not inherted from ICRUDAppService, how can I get the client side proxies generated? in normal abp there is swag utility to generate all the service proxies, but I can't find it in your project, any idea?

**Comment by sachatrauwaen** [comment]
OpenApp use the standard Abp proxies for the Application services.
We integrate also typescript definition generation from swagger.
And also json schema generation for the application services and dtos for the dynamic UI generation. 

This project is based on the mvc Abp template wich not include by default abp swagger proxies generation

**Comment by mawroos** [comment]
I have noticed this, so all good thanks
